# Generated by Django 4.2.26 on 2025-11-17 17:06

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('design_requests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='designrequest',
            name='design_request_name_lower_uniq',
        ),
        migrations.AlterField(
            model_name='designrequest',
            name='status',
            field=models.CharField(choices=[('н', 'Новая'), ('п', 'Принято в работу'), ('в', 'Выполнено')], default='н', max_length=1),
        ),
        migrations.AddConstraint(
            model_name='designrequest',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='design_request_name_lower_uniq', violation_error_message='Заявка с таким названием уже существует'),
        ),
    ]
