# Generated by Django 4.2.26 on 2025-11-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_requests', '0002_remove_designrequest_design_request_name_lower_uniq_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designrequest',
            name='photo',
            field=models.ImageField(help_text='Фото помещения', upload_to='user_photos/'),
        ),
    ]
