# Generated by Django 4.2.26 on 2025-11-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_requests', '0003_alter_designrequest_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': (('can_manage_categories', 'Пользователь может управлять категориями'),), 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='designrequest',
            options={'permissions': (('can_manage_requests', 'Пользователь может редактировать заявки'),), 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AddField(
            model_name='designrequest',
            name='comment',
            field=models.TextField(help_text='Комментарий при принятии в работу', null=True),
        ),
        migrations.AddField(
            model_name='designrequest',
            name='design_photo',
            field=models.ImageField(help_text='Готовый дизайн (только при статусе "Выполнено")', null=True, upload_to='designs/'),
        ),
    ]
